### ISSUE TITLE
Login Error on Windows

### ISSUE THREAD

**Issue by AxelTheAs** [Rokoko/rokoko-studio-live-blender#48] opened 2020-07-31 10:23 UTC
Hello I can't login on Windows 10, Blender 2.83

I have an error message:

![Rokoko Blender](https://user-images.githubusercontent.com/3631399/89026159-78610c00-d328-11ea-8b12-e6909ae7b126.jpg)

(I removed the login ID from the screen).

Also, I don't understand why is it necessary to login to access the features

**Comment by Darkblader24** [comment] 2020-07-31 11:08
Hey, this will be fixed when the full version gets released very soon.

**Comment by Darkblader24** [comment] 2020-07-31 16:05
The update is released, please update the plugin via the build-in updater and tell me if it works now.

**Comment by AxelTheAs** [comment] 2020-07-31 16:24
Hi Darkblader, Thanks for your reply.
I still have the same error after updating to 1.1.1 via Blender and restart the software.
I'm using Blender 2..83.2 for information.

**Comment by Darkblader24** [comment] 2020-07-31 17:56
Thanks for the response. I'm still trying to figure out the cause for this. Can you please install the Microsoft Visual C++ Package from here and then try to log in again: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
Choose the following download option: https://i.imgur.com/Sexi7qC.png

**Comment by AxelTheAs** [comment] 2020-07-31 21:41
Hi, I installed the package and still have the same error.

**Comment by Darkblader24** [comment] 2020-08-01 10:16
Thanks for trying it out. I have added another potential fix to the beta branch. Can you please update to the beta version via the build-in updater and give it another try?

**Comment by AxelTheAs** [comment] 2020-08-01 19:02
Hi,
I updated but it was still version 1.1.1. I tried anyway, same message.
Could it help if try on another blender version?

**Comment by Darkblader24** [comment] 2022-04-30 10:15
This Issue is now resolved!

**Closed by Darkblader24** 2022-04-30 10:15 UTC
