### ISSUE TITLE
Error activating plugin in blender

### ISSUE THREAD

**Issue by JustRender** [Rokoko/rokoko-studio-live-blender#69] opened 2021-05-21 12:57 UTC
**How me fix this error**?

Traceback (most recent call last):
  File "E:\Users\Titan\Downloads\blender_2.93.0_beta\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "E:\Users\Titan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rokoko-studio-live-blender-1-2-1\__init__.py", line 21, in <module>
    from . import core
  File "E:\Users\Titan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rokoko-studio-live-blender-1-2-1\core\__init__.py", line 3, in <module>
    from . import receiver
  File "E:\Users\Titan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rokoko-studio-live-blender-1-2-1\core\receiver.py", line 4, in <module>
    from . import animations, utils
  File "E:\Users\Titan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rokoko-studio-live-blender-1-2-1\core\animations.py", line 5, in <module>
    from .live_data_manager import LiveData
  File "E:\Users\Titan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rokoko-studio-live-blender-1-2-1\core\live_data_manager.py", line 5, in <module>
    from ..packages.win.lz4 import frame
  File "E:\Users\Titan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\rokoko-studio-live-blender-1-2-1\packages\win\lz4\__init__.py", line 14, in <module>
    from ._version import (  # noqa: F401
ModuleNotFoundError: No module named 'rokoko-studio-live-blender-1-2-1.packages.win.lz4._version'

**Comment by Hunanbean** [comment] 2021-06-04 23:56
Same problem here. Blender 2.93.0lts

**Comment by Topher-Farris** [comment] 2021-06-07 15:40
Same issue, tried various ways to install it, same result every time.

**Comment by sanskarbiswal** [comment] 2021-06-16 06:09
I too have the same issue. I tried to install from other branches as well but to no avail. However, the addon is still functional in Blender 2.90.1

**Comment by zakariya2004** [comment] 2021-06-17 07:35
I too get the same error while trying to enable rokoko addon :(

**Comment by Darkblader24** [comment] 2021-06-19 08:45
Thanks for the reports! This has been fixed in the beta version and will be released soon.

**Comment by maxhudetz** [comment] 2021-06-19 18:27
> Thanks for the reports! This has been fixed in the beta version and will be released soon.

having this problem as well, any ETA on the new version?

**Comment by sanskarbiswal** [comment] 2021-06-19 18:36
> > Thanks for the reports! This has been fixed in the beta version and will be released soon.
> 
> having this problem as well, any ETA on the new version?

You can download the beta release and add that as an addon...

**Comment by maxhudetz** [comment] 2021-06-19 18:56
> > > Thanks for the reports! This has been fixed in the beta version and will be released soon.
> > 
> > 
> > having this problem as well, any ETA on the new version?
> 
> You can download the beta release and add that as an addon...

THANK YOU for telling my dumb ass that it was out currently. Also, a tip to anyone else running portable version of blender from  a dropbox folder: disable dropbox sync or this update will not work. Cheers!

**Comment by HeCorr** [comment] 2022-05-28 01:57
I'm having the same issue. it says "Failed to load the plugin", then I try installing it, it says "please restart Blender" but when I do it's back to not being installed. installing the beta version does the exact same.

I'm running Blender portable btw, not an actual instalation.

**Comment by Darkblader24** [comment] 2022-05-28 05:03
Can you please go into the console and send me the log? You can open the console in blender via Window > Toggle System Console

**Comment by HeCorr** [comment] 2022-06-04 02:37
hello @Darkblader24, my sincere apologies for the one week delay in replying. I've been very busy.

Here's the console log as requested:

<details><summary>3.0.1 console log</summary>

```
addon_utils.disable: rokoko-studio-live-blender-1-4-0 not disabled
Modules Installed (rokoko-studio-live-blender-1-4-0) from 'D:\\_Blender\\Addons\\rokoko-studio-live-blender-1-4-0.zip' into 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons'

### Loading Rokoko Studio Live for Blender...
LOADED UPDATER!
Ensuring pip
Looking in links: c:\Users\user\AppData\Local\Temp\tmp0sd6advp
Requirement already satisfied: setuptools in d:\_blender\_versions\blender-3.0.1-windows-x64\3.0\python\lib\site-packages (57.4.0)
Requirement already satisfied: pip in c:\users\user\appdata\roaming\python\python39\site-packages (21.1.3)Updating pip
Requirement already satisfied: pip in c:\users\user\appdata\roaming\python\python39\site-packages (21.1.3)Collecting pip
  Downloading pip-22.1.2-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 3.3 MB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.1.3
    Uninstalling pip-21.1.3:
      Successfully uninstalled pip-21.1.3
  Rolling back uninstall of pip
  Moving to c:\users\user\appdata\roaming\python\python39\scripts\pip.exe
   from C:\Users\user\AppData\Local\Temp\pip-uninstall-11lebyje\pip.exe
  Moving to c:\users\user\appdata\roaming\python\python39\scripts\pip3.9.exe
   from C:\Users\user\AppData\Local\Temp\pip-uninstall-11lebyje\pip3.9.exe
  Moving to c:\users\user\appdata\roaming\python\python39\scripts\pip3.exe
   from C:\Users\user\AppData\Local\Temp\pip-uninstall-11lebyje\pip3.exe
  Moving to c:\users\user\appdata\roaming\python\python39\site-packages\pip-21.1.3.dist-info\
   from C:\Users\user\AppData\Roaming\Python\Python39\site-packages\~ip-21.1.3.dist-info
  Moving to c:\users\user\appdata\roaming\python\python39\site-packages\pip\
   from C:\Users\user\AppData\Roaming\Python\Python39\site-packages\~ip
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\commands\install.py", line 393, in run
    installed = install_given_reqs(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\req\__init__.py", line 77, in install_given_reqs
    requirement.install(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\req\req_install.py", line 787, in install
    install_wheel(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\install\wheel.py", line 810, in install_wheel
    _install_wheel(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\install\wheel.py", line 720, in _install_wheel
    generated_console_scripts = maker.make_multiple(scripts_to_generate)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 418, in make_multiple
    filenames.extend(self.make(specification, options))
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\install\wheel.py", line 462, in make
    return super().make(specification, options)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 407, in make
    self._make_script(entry, filenames, options=options)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 307, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 242, in _write_script
    launcher = self._get_launcher('t')
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 386, in _get_launcher
    raise ValueError(msg)
ValueError: Unable to find resource t64.exe in package pip._vendor.distlib
WARNING: You are using pip version 21.1.3; however, version 22.1.2 is available.
You should consider upgrading via the 'D:\_Blender\_Versions\blender-3.0.1-windows-x64\3.0\python\bin\python.EXE -m pip install --upgrade pip' command.
PIP Error: Command '['D:\\_Blender\\_Versions\\blender-3.0.1-windows-x64\\3.0\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--upgrade', 'pip']' returned non-zero exit status 2.
Updating pip failed.

Installing missing libraries: ['websockets', 'gql', 'cryptography', 'boto3']
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\commands\install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\resolvelib\resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\resolvelib\resolvers.py", line 341, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\resolvelib\structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 33, in _iter_built
    candidate = func()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 200, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 306, in __init__
    super().__init__(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 317, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\prepare.py", line 550, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\prepare.py", line 239, in unpack_url
    file = get_http_url(
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\operations\prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\network\download.py", line 157, in __call__
    for chunk in chunks:
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\progress_bars.py", line 156, in iter
    self.next(len(x))  # noqa: B305
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\progress\__init__.py", line 120, in next
    self.update()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\progress\bar.py", line 83, in update
    self.writeln(line)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\progress\__init__.py", line 102, in writeln
    print(line, end='', file=self.file)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "D:\_Blender\_Versions\blender-3.0.1-windows-x64\3.0\python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 6-8: character maps to <undefined>
WARNING: You are using pip version 21.1.3; however, version 22.1.2 is available.
You should consider upgrading via the 'D:\_Blender\_Versions\blender-3.0.1-windows-x64\3.0\python\bin\python.EXE -m pip install --upgrade pip' command.
PIP Error: Command '['D:\\_Blender\\_Versions\\blender-3.0.1-windows-x64\\3.0\\python\\bin\\python.EXE', '-m', 'pip', 'install', '--target=C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\3.0\\scripts\\addons\\rokoko-studio-live-blender-1-4-0\\resources\\libraries\\python39', 'websockets', 'gql', 'cryptography', 'boto3']' returned non-zero exit status 2.
Installing libraries failed.

WARNING: Could not install the following libraries: ['websockets', 'gql', 'cryptography', 'boto3']

ERROR: Rokoko plugin failed to load:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\rokoko-studio-live-blender-1-4-0\__init__.py", line 218, in register
    register_late()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\rokoko-studio-live-blender-1-4-0\__init__.py", line 238, in register_late
    raise ImportError("The following libraries could not be installed: " + str(missing))
ImportError: The following libraries could not be installed: ['websockets', 'gql', 'cryptography', 'boto3']
```

</details>

**Comment by dexterhuh** [comment] 2022-08-18 14:47
> 

I got exactly the same issue as HeCorr. Totally the same log.

**Comment by RobertDavidovic** [comment] 2022-12-26 08:18
Had the same issue, it's caused by the pip version in blender not updating correctly which can be fixed manually by running "C:\\Program Files\\Blender Foundation\\Blender 2.92\\2.92\\python\\bin\\python.EXE" -m pip install --upgrade pip. (For blender 2.92)

**Comment by LuDoSniper** [comment] 2023-04-26 20:37
Hi ! I have the same problem : I can't update rokoko so i can't enable it properly. I can't use it with using N. Have someone a sollution ?

**Comment by Frigginjosh** [comment] 2023-06-21 22:01
Hello @Darkblader24 I am working on blender 3.2 and having the same issue with rokoko plugin. how do fix it?

**Comment by Darkblader24** [comment] 2023-06-22 07:45
Hey, can you please update to the beta version of the plugin and let me know if it works there?
Either install it via the built-in updater or install this: https://github.com/Rokoko/rokoko-studio-live-blender/archive/refs/heads/beta.zip

**Comment by Darkblader24** [comment] 2023-06-22 14:31
Awesome, thank you!

**Closed by Darkblader24** 2023-06-22 14:31 UTC

**Comment by Frigginjosh** [comment] 2023-06-22 17:14
I updated to the beta and rokoko tab was available. In there was an option to download required libararies but when I clicked on it i got another error.
Here the console log of the error
Unable to install the libraries!
Try running Blender as an admin and install the libraries again.

Full Error: 

Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\rokoko-studio-live-blender-beta\operators\login.py", line 48, in execute
    self.install_libs()
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\rokoko-studio-live-blender-beta\operators\login.py", line 81, in install_libs
    missing = library_manager.lib_manager.install_libraries(["websockets", "gql", "cryptography", "boto3"])
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\rokoko-studio-live-blender-beta\core\library_manager.py", line 56, in install_libraries
    self._update_pip()
  File "C:\Users\DELL\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\rokoko-studio-live-blender-beta\core\library_manager.py", line 129, in _update_pip
    ensurepip.bootstrap()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\ensurepip\__init__.py", line 136, in bootstrap
    _bootstrap(root=root, upgrade=upgrade, user=user,
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\ensurepip\__init__.py", line 203, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\ensurepip\__init__.py", line 104, in _run_pip
    return subprocess.run(cmd, check=True).returncode
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software

**Comment by Darkblader24** [comment] 2023-06-22 18:45
Oh wow, that is quite interesting! So it looks like Windows Defender is blocking the process. It is weird because the part where it fails is where it tries to update pip, which is a trusted Python library.

Can you try starting Blender as an admin and installing the libraries again? Otherwise try excluding the Blender installation directory from Windows Defender.

**Comment by Frigginjosh** [comment] 2023-06-23 01:27
I tried both methods but still the same error

**Comment by Darkblader24** [comment] 2023-06-23 06:33
Ok, you can also try to temporarily disable your firewall and/or Antivirus software.

**Comment by Bil97** [comment] 2023-10-03 19:55
The plugin can't be activated when my computer is not connected to the internet. How do I use it without having to connect to the internet first?

**Comment by Darkblader24** [comment] 2023-10-03 19:58
> The addon can't be activated when my computer is not connected to the internet. I'm not always connect to the internet. How do I use it without having to connect to the internet first?

The plugin requires a internet connection during the first time setup and login. After that it should work with no internet

**Comment by Bil97** [comment] 2023-10-04 06:33
I'm using the latest version (1.4.1) with blender 3.6. I setup it up and it worked fine. But when I restart blender without internet, it won't show up in the tools menu. When I check in the add-ons panel it shows an error. I have alot of retargeting to do.
Error from add-ons pannel:
![Screenshot 2023-10-04 092808](https://github.com/Rokoko/rokoko-studio-live-blender/assets/36190575/cbcf6131-0028-4a49-ba7f-0d24412cf2fa)
Tools panel:
![Screenshot 2023-10-04 092740](https://github.com/Rokoko/rokoko-studio-live-blender/assets/36190575/cc1ccf7f-f6e5-4d11-8061-be7ca11c43fa)

Console:
![Screenshot 2023-10-02 162807](https://github.com/Rokoko/rokoko-studio-live-blender/assets/36190575/e9846108-9423-4ac6-94c1-49a00bbc6412)

**Comment by Bil97** [comment] 2023-10-08 11:01
I updated the addon to 1.4.2, now it works fine. Thanks alot

**Comment by empanadas11** [comment] 2024-06-03 07:18
> Oye, ¿puedes actualizar a la versión beta del complemento y decirme si funciona allí? Instálelo a través del actualizador incorporado o instale esto: https://github.com/Rokoko/rokoko-studio-live-blender/archive/refs/heads/beta.zip

si funciona

**Comment by tasleemansari6285** [comment] 2025-04-05 01:17
just turn off windows defender antivirus it will starting working again

**Comment by Bil97** [comment] 2025-04-05 12:39
Windows defender is not the problem for me, I must be connected to the internet when loading blender for it to work
